/*
 * Genome Nexus API
 * Genome Nexus Variant Annotation API
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.genome_nexus.client;

import org.genome_nexus.ApiException;
import org.genome_nexus.client.PostTranslationalModification;
import org.genome_nexus.client.PtmFilter;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PtmControllerApi
 */
@Ignore
public class PtmControllerApiTest {

    private final PtmControllerApi api = new PtmControllerApi();

    
    /**
     * Retrieves PTM entries by Ensembl Transcript IDs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostTranslationalModificationsByPtmFilterPOSTTest() throws ApiException {
        PtmFilter ptmFilter = null;
        List<PostTranslationalModification> response = api.fetchPostTranslationalModificationsByPtmFilterPOST(ptmFilter);

        // TODO: test validations
    }
    
    /**
     * Retrieves PTM entries by Ensembl Transcript ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchPostTranslationalModificationsGETTest() throws ApiException {
        String ensemblTranscriptId = null;
        List<PostTranslationalModification> response = api.fetchPostTranslationalModificationsGET(ensemblTranscriptId);

        // TODO: test validations
    }
    
}
